# Generated by Django 4.1.5 on 2023-05-21 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='is_registered',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='students',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
