# Generated by Django 4.1.5 on 2023-05-22 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentic', '0002_alter_students_is_registered_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('qualification', models.TextField()),
                ('is_registered', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('password', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('instructor_username', models.CharField(max_length=50)),
                ('is_allowed', models.BooleanField(default=False)),
                ('duration', models.IntegerField()),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
