# Generated by Django 4.1.5 on 2023-05-22 06:47

import authentic.models
from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('authentic', '0003_admin_instructor_subject'),
    ]

    operations = [
        migrations.DeleteModel(
            name='subject',
        ),
        migrations.AddField(
            model_name='students',
            name='subject',
            field=djongo.models.fields.ArrayField(default=None, model_container=authentic.models.subject),
        ),
    ]
