# Generated by Django 4.1.5 on 2023-05-22 06:48

import authentic.models
from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('authentic', '0004_delete_subject_students_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='subject',
            field=djongo.models.fields.ArrayField(default=None, model_container=authentic.models.subject),
        ),
    ]
