# Generated by Django 4.1.5 on 2023-05-22 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentic', '0005_instructor_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AddField(
            model_name='instructor',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AddField(
            model_name='students',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
    ]
